'use server';

import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';

export type RedemptionStatus =
  | 'expired'
  | 'rejected'
  | 'membership_invalid'
  | 'rule_blocked'
  | 'server_error';

export type ScanResult =
  | { token_type: 'redemption'; valid: true; offer_title: string; benefit_text: string | null; consumer_name: string | null }
  | {
      token_type: 'redemption';
      valid: false;
      status: RedemptionStatus;
      rejection_reason: string;
      next_available_at: string | null;
    }
  | { token_type: 'membership_pass'; valid: true; plan_interval: string; member_since: string | null }
  | { token_type: 'membership_pass'; valid: false }
  | { token_type: 'unknown'; valid: false; rejection_reason: string };

/**
 * Server action: validates a scanned QR token via the validate-qr-token edge
 * function. All business logic, DB writes, and offer rule enforcement are
 * handled in the edge function and redeem_offer_token RPC.
 *
 * Supports both token types without the caller needing to know which was scanned:
 *  - redemption tokens (offer-specific, single-use, validated via RPC transaction)
 *  - membership pass tokens (membership proof, reusable within 5-min TTL)
 *
 * attemptId must be generated by the caller when the QR is first decoded and
 * reused on any retry of the same decoded token. This gives the RPC idempotency:
 * a duplicate call with the same attemptId returns the cached result without
 * re-processing. A fresh scan always supplies a new attemptId.
 *
 * Required env vars:
 *   NEXT_PUBLIC_SUPABASE_URL
 *   NEXT_PUBLIC_SUPABASE_ANON_KEY
 */
export async function validateRedemption(
  rawToken: string,
  attemptId: string,
): Promise<ScanResult> {
  const supabase = await createClient();
  const { data: { session } } = await supabase.auth.getSession();
  if (!session) redirect('/sign-in');

  let res: Response;
  try {
    res = await fetch(
      `${process.env.NEXT_PUBLIC_SUPABASE_URL}/functions/v1/validate-qr-token`,
      {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${session.access_token}`,
          'Content-Type': 'application/json',
          apikey: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
        },
        body: JSON.stringify({
          token: rawToken.trim(),
          redemption_attempt_id: attemptId,
        }),
      },
    );
  } catch {
    return {
      token_type: 'unknown',
      valid: false,
      rejection_reason: 'Could not reach validation server. Check your connection and try again.',
    };
  }

  if (res.status === 401) redirect('/sign-in');

  // Parse body for all status codes — needed to differentiate 403 variants.
  let body: Record<string, unknown>;
  try {
    body = await res.json();
  } catch {
    return {
      token_type: 'unknown',
      valid: false,
      rejection_reason: 'Unexpected server response. Please try again.',
    };
  }

  if (res.status === 403) {
    // Forbidden = retailer user no longer valid; Membership not active = pass path.
    if (body.error === 'Forbidden') redirect('/sign-in');
    return { token_type: 'membership_pass', valid: false };
  }

  if (res.status === 404) {
    return {
      token_type: 'unknown',
      valid: false,
      rejection_reason: 'QR code not recognised. Ask the member to open their app and try again.',
    };
  }

  if (res.status === 410) {
    // Membership pass token expired.
    return { token_type: 'membership_pass', valid: false };
  }

  if (!res.ok) {
    return {
      token_type: 'unknown',
      valid: false,
      rejection_reason: 'Validation failed. Please try again.',
    };
  }

  // ── 200 OK: parse business outcome ───────────────────────────────────────
  if (body.token_type === 'membership_pass') {
    if (body.valid === true) {
      return {
        token_type: 'membership_pass',
        valid: true,
        plan_interval: (body.plan_interval as string | null) ?? 'monthly',
        member_since: (body.member_since as string | null) ?? null,
      };
    }
    return { token_type: 'membership_pass', valid: false };
  }

  if (body.token_type === 'redemption') {
    if (body.valid === true) {
      return {
        token_type: 'redemption',
        valid: true,
        offer_title: (body.offer_title as string | null) ?? 'Offer',
        benefit_text: (body.benefit_text as string | null) ?? null,
        consumer_name: (body.consumer_name as string | null) ?? null,
      };
    }
    return {
      token_type: 'redemption',
      valid: false,
      status: (body.status as RedemptionStatus) ?? 'rejected',
      rejection_reason:
        (body.rejection_reason as string | null) ??
        'This QR code could not be validated.',
      next_available_at: (body.next_available_at as string | null) ?? null,
    };
  }

  return {
    token_type: 'unknown',
    valid: false,
    rejection_reason: 'Unrecognised response from server.',
  };
}
