-- 044_redemptions_visit_session.sql
-- Adds visit and scanner session grouping primitives to redemptions.
--
-- NOTE: scanner attribution (who processed the scan) is already covered by
-- the existing validated_by_profile_id column, which the redeem_offer_token
-- RPC populates from p_retailer_profile_id on every redemption insert.
-- No additional attribution column is needed.
--
-- visit_id
--   Groups redemptions that belong to the same customer visit.
--   Represents the domain entity: Consumer → Visit → Redemption(s).
--   NULL for all current records and until the scanner visit workflow ships.
--   Not enforced. Future use: visit analytics, max_offers_per_visit checks,
--   repeat visit behaviour metrics.
--
-- scanner_session_id
--   The scanner UI session during which this redemption was processed.
--   Generated by the scanner app at the start of each customer interaction.
--   Shared across "Add another offer" redemptions within one interaction.
--   Distinct from visit_id: scanner_session_id traces directly to the
--   scanner workflow; visit_id is the logical customer-facing grouping.
--   At initial implementation these will carry the same UUID per interaction.
--   NULL for all current records and until scanner visit workflow ships.
--   Not enforced.

alter table redemptions
  add column visit_id           uuid,
  add column scanner_session_id uuid;

comment on column redemptions.visit_id is
  'Groups redemptions within one customer visit. Set by scanner when visit grouping ships. NULL until then.';

comment on column redemptions.scanner_session_id is
  'The scanner UI session that processed this redemption. Set by scanner when visit workflow ships. NULL until then.';
