import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

// ---------------------------------------------------------------------------
// Shared icon key → Flutter IconData mapping
//
// SYNC REQUIREMENT: This map mirrors the curated icon list in
//   apps/admin/components/material_icon_picker.tsx
//
// When new icons are added to the admin picker, add the matching Flutter
// IconData entry here. The map key must be the exact snake_case string saved
// in the DB (categories.icon column).
// ---------------------------------------------------------------------------

/// Maps Material Design icon name strings (as stored in `categories.icon`)
/// to Flutter [IconData].
const Map<String, IconData> kMaterialIconMap = {
  // ── Food & Drink ──────────────────────────────────────────────────────────
  'bakery_dining':       Icons.bakery_dining,
  'bento':               Icons.bento,
  'breakfast_dining':    Icons.breakfast_dining,
  'brunch_dining':       Icons.brunch_dining,
  'cake':                Icons.cake,
  'coffee':              Icons.coffee,
  'cookie':              Icons.cookie,
  'dinner_dining':       Icons.dinner_dining,
  'egg':                 Icons.egg,
  'emoji_food_beverage': Icons.emoji_food_beverage,
  'fastfood':            Icons.fastfood,
  'icecream':            Icons.icecream,
  'kebab_dining':        Icons.kebab_dining,
  'liquor':              Icons.liquor,
  'local_bar':           Icons.local_bar,
  'local_cafe':          Icons.local_cafe,
  'local_drink':         Icons.local_drink,
  'local_pizza':         Icons.local_pizza,
  'lunch_dining':        Icons.lunch_dining,
  'ramen_dining':        Icons.ramen_dining,
  'restaurant':          Icons.restaurant,
  'set_meal':            Icons.set_meal,
  'sports_bar':          Icons.sports_bar,
  'tapas':               Icons.tapas,
  'wine_bar':            Icons.wine_bar,

  // ── Shopping & Retail ─────────────────────────────────────────────────────
  'card_giftcard':            Icons.card_giftcard,
  'inventory':                Icons.inventory,
  'inventory_2':              Icons.inventory_2,
  'local_atm':                Icons.local_atm,
  'local_convenience_store':  Icons.local_convenience_store,
  'local_grocery_store':      Icons.local_grocery_store,
  'local_mall':               Icons.local_mall,
  'local_offer':              Icons.local_offer,
  'loyalty':                  Icons.loyalty,
  'point_of_sale':            Icons.point_of_sale,
  'receipt':                  Icons.receipt,
  'receipt_long':             Icons.receipt_long,
  'redeem':                   Icons.redeem,
  'sell':                     Icons.sell,
  'shopping_bag':             Icons.shopping_bag,
  'shopping_basket':          Icons.shopping_basket,
  'shopping_cart':            Icons.shopping_cart,
  'store':                    Icons.store,
  'storefront':               Icons.storefront,
  'warehouse':                Icons.warehouse,

  // ── Beauty, Wellness & Spa ────────────────────────────────────────────────
  'accessibility':            Icons.accessibility,
  'accessibility_new':        Icons.accessibility_new,
  'brush':                    Icons.brush,
  'checkroom':                Icons.checkroom,
  'colorize':                 Icons.colorize,
  'content_cut':              Icons.content_cut,
  'dry_cleaning':             Icons.dry_cleaning,
  'face':                     Icons.face,
  'face_retouching_natural':  Icons.face_retouching_natural,
  'local_laundry_service':    Icons.local_laundry_service,
  'palette':                  Icons.palette,
  'self_improvement':         Icons.self_improvement,
  'spa':                      Icons.spa,

  // ── Health & Medical ──────────────────────────────────────────────────────
  'biotech':            Icons.biotech,
  'bloodtype':          Icons.bloodtype,
  'coronavirus':        Icons.coronavirus,
  'emergency':          Icons.emergency,
  'favorite':           Icons.favorite,
  'favorite_border':    Icons.favorite_border,
  'healing':            Icons.healing,
  'health_and_safety':  Icons.health_and_safety,
  'local_hospital':     Icons.local_hospital,
  'local_pharmacy':     Icons.local_pharmacy,
  'medical_services':   Icons.medical_services,
  'medication':         Icons.medication,
  'monitor_heart':      Icons.monitor_heart,
  'psychology':         Icons.psychology,
  'science':            Icons.science,
  'sick':               Icons.sick,
  'vaccines':           Icons.vaccines,
  'volunteer_activism': Icons.volunteer_activism,

  // ── Fitness & Sports ──────────────────────────────────────────────────────
  'bicycle':              Icons.bicycle,
  'directions_bike':      Icons.directions_bike,
  'directions_run':       Icons.directions_run,
  'downhill_skiing':      Icons.downhill_skiing,
  'fitness_center':       Icons.fitness_center,
  'hiking':               Icons.hiking,
  'hot_tub':              Icons.hot_tub,
  'kayaking':             Icons.kayaking,
  'nordic_walking':       Icons.nordic_walking,
  'paragliding':          Icons.paragliding,
  'pool':                 Icons.pool,
  'roller_skating':       Icons.roller_skating,
  'rowing':               Icons.rowing,
  'sailing':              Icons.sailing,
  'skateboarding':        Icons.skateboarding,
  'snowboarding':         Icons.snowboarding,
  'sports':               Icons.sports,
  'sports_baseball':      Icons.sports_baseball,
  'sports_basketball':    Icons.sports_basketball,
  'sports_cricket':       Icons.sports_cricket,
  'sports_esports':       Icons.sports_esports,
  'sports_football':      Icons.sports_football,
  'sports_golf':          Icons.sports_golf,
  'sports_gymnastics':    Icons.sports_gymnastics,
  'sports_handball':      Icons.sports_handball,
  'sports_hockey':        Icons.sports_hockey,
  'sports_mma':           Icons.sports_mma,
  'sports_motorsports':   Icons.sports_motorsports,
  'sports_rugby':         Icons.sports_rugby,
  'sports_soccer':        Icons.sports_soccer,
  'sports_tennis':        Icons.sports_tennis,
  'sports_volleyball':    Icons.sports_volleyball,
  'surfing':              Icons.surfing,

  // ── Travel & Hospitality ──────────────────────────────────────────────────
  'apartment':          Icons.apartment,
  'beach_access':       Icons.beach_access,
  'cabin':              Icons.cabin,
  'cottage':            Icons.cottage,
  'directions_boat':    Icons.directions_boat,
  'directions_bus':     Icons.directions_bus,
  'directions_car':     Icons.directions_car,
  'directions_transit': Icons.directions_transit,
  'ev_station':         Icons.ev_station,
  'explore':            Icons.explore,
  'flight':             Icons.flight,
  'forest':             Icons.forest,
  'holiday_village':    Icons.holiday_village,
  'hotel':              Icons.hotel,
  'landscape':          Icons.landscape,
  'local_airport':      Icons.local_airport,
  'local_gas_station':  Icons.local_gas_station,
  'local_taxi':         Icons.local_taxi,
  'luggage':            Icons.luggage,
  'map':                Icons.map,
  'night_shelter':      Icons.night_shelter,
  'park':               Icons.park,
  'subway':             Icons.subway,
  'train':              Icons.train,
  'tram':               Icons.tram,
  'travel_explore':     Icons.travel_explore,
  'villa':              Icons.villa,

  // ── Home & Living ─────────────────────────────────────────────────────────
  'ac_unit':        Icons.ac_unit,
  'balcony':        Icons.balcony,
  'bathroom':       Icons.bathroom,
  'bathtub':        Icons.bathtub,
  'bed':            Icons.bed,
  'bedroom_parent': Icons.bedroom_parent,
  'blender':        Icons.blender,
  'chair':          Icons.chair,
  'countertops':    Icons.countertops,
  'fence':          Icons.fence,
  'fireplace':      Icons.fireplace,
  'foundation':     Icons.foundation,
  'garage':         Icons.garage,
  'grass':          Icons.grass,
  'home':           Icons.home,
  'house':          Icons.house,
  'kitchen':        Icons.kitchen,
  'light':          Icons.light,
  'living':         Icons.living,
  'microwave':      Icons.microwave,
  'roofing':        Icons.roofing,
  'shower':         Icons.shower,
  'wb_sunny':       Icons.wb_sunny,
  'weekend':        Icons.weekend,
  'yard':           Icons.yard,

  // ── Services & Trades ─────────────────────────────────────────────────────
  'anchor':               Icons.anchor,
  'build':                Icons.build,
  'cable':                Icons.cable,
  'carpenter':            Icons.carpenter,
  'cleaning_services':    Icons.cleaning_services,
  'construction':         Icons.construction,
  'design_services':      Icons.design_services,
  'electrical_services':  Icons.electrical_services,
  'format_paint':         Icons.format_paint,
  'handyman':             Icons.handyman,
  'hardware':             Icons.hardware,
  'home_repair_service':  Icons.home_repair_service,
  'hvac':                 Icons.hvac,
  'manage_accounts':      Icons.manage_accounts,
  'plumbing':             Icons.plumbing,

  // ── Automotive ────────────────────────────────────────────────────────────
  'car_repair':      Icons.car_repair,
  'electric_car':    Icons.electric_car,
  'fire_truck':      Icons.fire_truck,
  'local_car_wash':  Icons.local_car_wash,
  'local_police':    Icons.local_police,
  'local_shipping':  Icons.local_shipping,
  'oil_barrel':      Icons.oil_barrel,
  'tire_repair':     Icons.tire_repair,
  'two_wheeler':     Icons.two_wheeler,

  // ── Education ─────────────────────────────────────────────────────────────
  'assignment':         Icons.assignment,
  'auto_stories':       Icons.auto_stories,
  'book':               Icons.book,
  'calculate':          Icons.calculate,
  'class':              Icons.class_,
  'create':             Icons.create,
  'description':        Icons.description,
  'edit':               Icons.edit,
  'emoji_events':       Icons.emoji_events,
  'grading':            Icons.grading,
  'history_edu':        Icons.history_edu,
  'library_books':      Icons.library_books,
  'local_library':      Icons.local_library,
  'menu_book':          Icons.menu_book,
  'military_tech':      Icons.military_tech,
  'quiz':               Icons.quiz,
  'school':             Icons.school,
  'stars':              Icons.stars,
  'workspace_premium':  Icons.workspace_premium,

  // ── Entertainment & Activities ────────────────────────────────────────────
  'album':           Icons.album,
  'attractions':     Icons.attractions,
  'casino':          Icons.casino,
  'celebration':     Icons.celebration,
  'dark_mode':       Icons.dark_mode,
  'festival':        Icons.festival,
  'headphones':      Icons.headphones,
  'library_music':   Icons.library_music,
  'live_tv':         Icons.live_tv,
  'local_activity':  Icons.local_activity,
  'mic':             Icons.mic,
  'movie':           Icons.movie,
  'music_note':      Icons.music_note,
  'nightlife':       Icons.nightlife,
  'outdoor_grill':   Icons.outdoor_grill,
  'piano':           Icons.piano,
  'theater_comedy':  Icons.theater_comedy,
  'toys':            Icons.toys,
  'videogame_asset': Icons.videogame_asset,

  // ── Pets & Animals ────────────────────────────────────────────────────────
  'cruelty_free': Icons.cruelty_free,
  'pets':         Icons.pets,

  // ── Kids & Family ─────────────────────────────────────────────────────────
  'baby_changing_station': Icons.baby_changing_station,
  'child_care':            Icons.child_care,
  'child_friendly':        Icons.child_friendly,
  'crib':                  Icons.crib,
  'family_restroom':       Icons.family_restroom,
  'stroller':              Icons.stroller,

  // ── Technology ────────────────────────────────────────────────────────────
  'bluetooth':           Icons.bluetooth,
  'camera':              Icons.camera,
  'camera_alt':          Icons.camera_alt,
  'cloud':               Icons.cloud,
  'computer':            Icons.computer,
  'developer_mode':      Icons.developer_mode,
  'devices':             Icons.devices,
  'keyboard':            Icons.keyboard,
  'memory':              Icons.memory,
  'mouse':               Icons.mouse,
  'print':               Icons.print,
  'router':              Icons.router,
  'signal_cellular_alt': Icons.signal_cellular_alt,
  'smartphone':          Icons.smartphone,
  'storage':             Icons.storage,
  'tablet':              Icons.tablet,
  'tv':                  Icons.tv,
  'usb':                 Icons.usb,
  'videocam':            Icons.videocam,
  'watch':               Icons.watch,
  'wifi':                Icons.wifi,

  // ── Finance & Business ────────────────────────────────────────────────────
  'account_balance':   Icons.account_balance,
  'attach_money':      Icons.attach_money,
  'bar_chart':         Icons.bar_chart,
  'business':          Icons.business,
  'business_center':   Icons.business_center,
  'corporate_fare':    Icons.corporate_fare,
  'credit_card':       Icons.credit_card,
  'currency_exchange': Icons.currency_exchange,
  'domain':            Icons.domain,
  'money':             Icons.money,
  'payments':          Icons.payments,
  'real_estate_agent': Icons.real_estate_agent,
  'savings':           Icons.savings,
  'trending_up':       Icons.trending_up,
  'work':              Icons.work,

  // ── Communication ─────────────────────────────────────────────────────────
  'alternate_email': Icons.alternate_email,
  'chat':            Icons.chat,
  'contact_page':    Icons.contact_page,
  'email':           Icons.email,
  'forum':           Icons.forum,
  'headset_mic':     Icons.headset_mic,
  'notifications':   Icons.notifications,
  'phone':           Icons.phone,
  'sms':             Icons.sms,
  'support_agent':   Icons.support_agent,

  // ── Nature & Environment ──────────────────────────────────────────────────
  'air':                 Icons.air,
  'compost':             Icons.compost,
  'eco':                 Icons.eco,
  'energy_savings_leaf': Icons.energy_savings_leaf,
  'local_florist':       Icons.local_florist,
  'nights_stay':         Icons.nights_stay,
  'recycling':           Icons.recycling,
  'solar_power':         Icons.solar_power,
  'storm':               Icons.storm,
  'terrain':             Icons.terrain,
  'water':               Icons.water,
  'water_drop':          Icons.water_drop,
  'wb_cloudy':           Icons.wb_cloudy,
  'wind_power':          Icons.wind_power,

  // ── General & Utility ─────────────────────────────────────────────────────
  'badge':          Icons.badge,
  'check_circle':   Icons.check_circle,
  'diversity_1':    Icons.diversity_1,
  'diversity_2':    Icons.diversity_2,
  'diversity_3':    Icons.diversity_3,
  'flag':           Icons.flag,
  'grade':          Icons.grade,
  'groups':         Icons.groups,
  'handshake':      Icons.handshake,
  'help':           Icons.help,
  'info':           Icons.info,
  'link':           Icons.link,
  'location_city':  Icons.location_city,
  'location_on':    Icons.location_on,
  'lock':           Icons.lock,
  'lock_open':      Icons.lock_open,
  'near_me':        Icons.near_me,
  'new_releases':   Icons.new_releases,
  'place':          Icons.place,
  'qr_code':        Icons.qr_code,
  'share':          Icons.share,
  'star':           Icons.star,
  'star_border':    Icons.star_border,
  'support':        Icons.support,
  'thumb_up':       Icons.thumb_up,
  'tour':           Icons.tour,
  'verified':       Icons.verified,
  'visibility':     Icons.visibility,
};

/// Fallback icon rendered when [key] is null, empty, or not in [kMaterialIconMap].
const IconData kFallbackCategoryIcon = Icons.storefront;

/// Returns the [IconData] for [key], or [kFallbackCategoryIcon] if unknown.
///
/// In debug builds, logs a warning for unrecognised keys so new admin icons
/// can be detected and added to [kMaterialIconMap] promptly.
IconData iconDataForKey(String? key) {
  if (key == null || key.isEmpty) return kFallbackCategoryIcon;
  final icon = kMaterialIconMap[key];
  if (icon == null) {
    assert(() {
      debugPrint(
        '[MaterialIconMap] Unknown icon key: "$key" — add it to '
        'lib/core/utils/material_icon_map.dart and '
        'apps/admin/components/material_icon_picker.tsx',
      );
      return true;
    }());
    return kFallbackCategoryIcon;
  }
  return icon;
}
